### ISSUE TITLE
Wrong cdhash printed for SHA1 CODE_DIRECTORY

### ISSUE THREAD

**Issue by minkiux** [qyang-nj/llios#80]
`./macho_parser --cd <file>` prints sha256 cdhash regardless of hash type defined in CODE_DIRECTORY blob (CS_CodeDirectory).

Printed cdhash should match the hash algorithm.
i.e. if CODE_DIRECTORY uses SHA1, then cdhash should be computed with sha1().

https://github.com/qyang-nj/llios/blob/85198627998f1cbac91731ec9d0354f2a72f5b43/macho_parser/sources/code_signature.cpp#L130

**Comment by qyang-nj** [comment]
It's fixed. Thanks for reporting!
